---

- hosts: localhost
  become: no

  tasks:

    - name: Check for compatible Ansible version
      when: >
        ansible_version["string"] | version_compare("2.2", "<")
        or ansible_version["string"] | version_compare("2.9", ">=")
      fail:
        msg: >
          Your version of Ansible doesn't match the required version. Please
          install ansible-playbook with `pip install -r requirements.txt`.

- hosts: managed
  become: yes

  tasks:

    - name: Gather information from target server
      setup:

    - name: Check minimum CPU requirements
      fail:
        msg: "You need at least 2 vCPUs available, found {{ ansible_processor_vcpus }}"
      when: ansible_processor_vcpus < 2

    - name: Check minimum memory requirements
      fail:
        msg: "You need at least 8 Gb of memory available, found {{ ansible_memtotal_mb / 1024 }} Gb"
      when: ansible_memtotal_mb < 7500 and 'df' in mip_building_blocks

    - name: Check minimum memory requirements - without Data Factory
      fail:
        msg: "You need at least 4 Gb of memory available, found {{ ansible_memtotal_mb / 1024 }} Gb"
      when: ansible_memtotal_mb < 4000 and not 'df' in mip_building_blocks

    - name: Suggested target server hostname
      debug: var=ansible_hostname

    - name: Suggested target server FQDN
      debug: var=ansible_fqdn

    - name: Suggested target server IP address
      debug:
        msg: "{{ ansible_default_ipv4.address }}"

- hosts: localhost
  become: no
  vars_prompt:
    - name: "server_hostname"
      prompt: "Target server hostname, e.g. myserver . Use ansible_hostname value if you agree with it."
      private: no
    - name: "server_fqdn"
      prompt: "Target server FQDN, e.g. myserver.myorg.com . If the full server name cannot be reached by DNS (ping myserver.myorg.com fails), you can use the IP address instead"
      private: no
    - name: "server_ip_address"
      prompt: "Target server IP address"
      private: no
    - name: "portal_frontend_base_url"
      prompt: "Base URL for the frontend, for example http://myserver.myorg.com:7000"
      private: no
    - name: "gitlab_com_login"
      prompt: "Username on Gitlab to download private Docker images. Leave blank if you do not have access to this information"
      private: no
    - name: "gitlab_com_password"
      prompt: "Password on Gitlab to download private Docker images. Leave blank if you do not have access to this information"
      private: yes
    - name: "only_research_data"
      prompt: "Use research data only? (Y/n)"
      private: no

  roles:

    - role: mip-local
