---
#
# Master Install
#
# Installs _the_ world
#

- include: ../../common/playbooks/infrastructure/base-system.yml

- include: ../../common/playbooks/infrastructure/zookeeper.yml

- include: ../../common/playbooks/infrastructure/mesos-leader.yml

- include: ../../common/playbooks/infrastructure/mesos-mixed.yml

- include: ../../common/playbooks/infrastructure/mesos-follower.yml

- include: ../../common/playbooks/data-factory/airflow.yml

- include: ../../common/playbooks/ldsm-database.yml

- hosts: data-factory
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/airflow.yml"

  tasks:

    - name: Create group for Airflow
      group:
        name: '{{ airflow_group }}'
        state: present

    - name: Create user for Airflow
      user:
        name: '{{ airflow_user }}'
        group: '{{ airflow_group }}'
        home: '{{ airflow_home }}'

    - name: Create folders for data and scripts
      file: path='{{ item }}' state=directory owner=airflow
      with_items:
        - /data/demo

    - name: Get some MRI data from public datasets (it takes time)
      git:
        repo: https://github.com/dcunited001/mri-scans.git
        dest: /data/demo
        depth: 1
