---

# Cleanup old configurations and software

- hosts: managed
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/infrastructure/endpoints.yml"

  tasks:
    - name: Remove old packages
      apt: pkg="{{ item }}" state=absent
      with_items:
        - chronos # migrated to Docker
      when: ansible_distribution == "Ubuntu"
      tags: ['cleanup', 'infra', 'infrastructure']

    - name: Remove old files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /srv/docker/postgres
        - /opt/analytics-database
        - /srv/docker/analyticsdb
        - /etc/apt/sources.list.d/docker.list
        - /etc/chronos
        - /etc/apt/sources.list.d/apt_dockerproject_org_repo.list
        - /etc/apt/sources.list.d/repos_mesosphere_io_ubuntu.list
      tags: ['cleanup', 'infra', 'infrastructure']
