---
# Setup mandatory software on the control box

- hosts: control
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
  #  - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/infrastructure/endpoints.yml"

  handlers:
    - name: Inform installer needs restart
      debug:
        msg: "A library required by this installer was installed on the system. Please restart ./setup.sh to complete the installation"
      listen: "inform restart installer"

    - name: Installer needs restart
      fail:
        message: "A library required by this installer was installed on the system. Please restart ./setup.sh to complete the installation"
      listen: "restart installer"

  roles:

    - role: docker
      tags: ['docker', 'os-tools', 'control', 'infra', 'infrastructure']

  post_tasks:

    - name: (Ubuntu) Install Python psycopg2 module for Postgres (required by postgresql_db task), pip and curl (required for marathon-app)
      apt: name={{ item }} state=present
      with_items:
        - python-psycopg2
        - python-pip
        - curl
      when: ansible_os_family == 'Debian'
      tags: ['os-tools', 'control', 'infra', 'infrastructure']
      notify:
        - "inform restart installer"
        - "restart installer"

    - name: (RedHat) Install Python psycopg2 module for Postgres (required by postgresql_db task), pip and curl (required for marathon-app)
      yum: name={{ item }} state=present
      with_items:
        - python-pip
        - python-devel
        - gcc
        - openssl-devel
        - curl
      when: ansible_os_family == 'RedHat'
      tags: ['os-tools', 'control', 'infra', 'infrastructure']
      notify:
        - "inform restart installer"
        - "restart installer"

    - name: Install Python module for Docker (required by docker_container task)
      pip: name=docker-py state=present
      tags: ['docker', 'os-tools', 'control', 'infra', 'infrastructure']

    - name: Install Python module jmespath (required by Data factory tasks)
      pip: name='jmespath==0.9.3' state=present
      tags: ['data-factory', 'os-tools', 'control', 'infra', 'infrastructure']
      notify:
        - "inform restart installer"
        - "restart installer"

    - name: (RedHat) Install Python psycopg2 module for Postgres (required by postgresql_db task) and cryptography (required by airflow role)
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - psycopg2
        - cryptography
      when: ansible_os_family == 'RedHat'
      tags: ['os-tools', 'control', 'infra', 'infrastructure']
      notify:
        - "inform restart installer"
        - "restart installer"
